<?php if (! defined('BASEPATH')) exit('No direct script access allowed');

class Metadata_provenance
{
    public const TITLE = "Provenance";
    public const GENERATED_FROM_TEXT = "This metadata record was generated by the BSI MWLR Group Metadata Editor";
    private const TIMEZONE = 'UTC';
    private const NEW_ZEALAND_TIMEZONE = 'Pacific/Auckland';

    /** @var string */
    public $user_name;
    /** @var DateTimeImmutable */
    public $generated_on_new_zealand_time;
    /** @var DateTimeImmutable */
    public $generated_on_utc;


    public function __construct($user_name = null)
    {
        $date = new DateTimeImmutable('now');
        $this->user_name = $user_name ?? '';
        $this->generated_on_new_zealand_time = $date->setTimezone(new DateTimeZone(self::NEW_ZEALAND_TIMEZONE));
        $this->generated_on_utc = $date->setTimezone(new DateTimeZone(self::TIMEZONE));
    }
}
